### ISSUE TITLE
Plex integration - missing album graphic

### ISSUE THREAD

**Issue by apwiggins** [cvdlinden/wiim-now-playing#5]
WiiM recently added a beta Plex integration.  A minor issue presents itself:

Expected behaviour:
1. All song metadata is presented - source, song title, artist, album title, stream quality, album cover graphic

Actual behaviour:
1. All of the above are presented, except for the album cover graphic.
2. Instead, a dummy album cover graphic is presented.  Example screenshots.

![Screenshot from 2024-10-15 08-16-43](https://github.com/user-attachments/assets/8784f75c-b87c-485e-8eb8-6f57c36ae3ff)
![Screenshot from 2024-10-15 08-18-41](https://github.com/user-attachments/assets/111fc118-3051-48b9-b6ff-742d8c227691)

**Comment by cvdlinden** [comment]
@apwiggins I haven't tested the Plex integration out myself, but I do have an idea why the cover art isn't showing. The UI simply isn't aware of it, yet. :)
Can you do the following for me? Play a song on Plex. Open a browser and browse to your WiiM Now Playing instance. You should see the normal UI. Now go to /debug (add it to the url).

You should see the debug page with the Metadata section, like:
![image](https://github.com/user-attachments/assets/7f1fb142-6997-4f6c-bc2e-e810b246f951)

It should show an 'Album Art URI' value, starting with http://... or https://...
If not, could you drop the contents of the Metadata field down here? If there's any personal identifying stuff in there, please remove it first. So I can have a look if there's anything to be done about recognizing the album art from Plex.

On a side note: These dummy album covers where added to hide any missing or unavailable cover art. :)
Also, I should add a Plex logo instead of the 'SONGLIST-NETWORK: Plex' label...

**Comment by apwiggins** [comment]
Tokens have been redacted.  Following the albumArtURI in a second browser (with the Token) does pull the right image (1000px by 1000px - below) from Plex, but it doesn't appear in WNP browser.

![1725937474](https://github.com/user-attachments/assets/01f2cbb5-f864-4485-8c3a-de0b75fbad12)

Metadata from debug window.
`{
    "trackMetaData": {
        "song:id": "/library/metadata/9795",
        "song:singerid": "/library/metadata/9793/children",
        "song:albumid": "/library/metadata/9794/children",
        "res": "https://192.168.1.33:32400/library/parts/27205/1655668124/file.flac?X-Plex-Token=REDACTED",
        "dc:title": "Sweetness and Light",
        "upnp:artist": "Lush",
        "upnp:album": "Gala",
        "upnp:albumArtURI": "https://192.168.1.33:32400/library/metadata/9794/thumb/1725937474?X-Plex-Token=REDACTED",
        "song:rate_hz": "44100",
        "song:format_s": "16",
        "song:bitrate": "944"
    },
    "CurrentTransportState": "PAUSED_PLAYBACK",
    "CurrentTransportStatus": "OK",
    "CurrentSpeed": "1",
    "Track": "1",
    "TrackDuration": "00:05:19",
    "TrackMetaData": "<?xml version=\"1.0\"?>\r\n<DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:song=\"www.linkplay.com/song/\" xmlns:custom=\"www.linkplay.com/custom/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\">\r\n<upnp:class>object.item.audioItem.musicTrack</upnp:class>\r\n<item id=\"/library/sections/3/stations/1\">\r\n<song:id>/library/metadata/9795</song:id>\r\n<song:singerid>/library/metadata/9793/children</song:singerid>\r\n<song:albumid>/library/metadata/9794/children</song:albumid>\r\n<res protocolInfo=\"http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;\" duration=\"319840\">https://192.168.1.33:32400/library/parts/27205/1655668124/file.flac?X-Plex-Token=REDACTED</res>\r\n<dc:title>Sweetness and Light</dc:title>\r\n<upnp:artist>Lush</upnp:artist>\r\n<upnp:album>Gala</upnp:album>\r\n<upnp:albumArtURI>https://192.168.1.33:32400/library/metadata/9794/thumb/1725937474?X-Plex-Token=REDACTED</upnp:albumArtURI>\r\n<song:rate_hz>44100</song:rate_hz>\r\n<song:format_s>16</song:format_s>\r\n<song:bitrate>944</song:bitrate>\r\n</item>\r\n</DIDL-Lite>\r\n",
    "TrackURI": "https://192.168.1.33:32400/library/parts/27205/1655668124/file.flac?X-Plex-Token=REDACTED",
    "RelTime": "00:00:17",
    "AbsTime": "NOT_IMPLEMENTED",
    "RelCount": "2147483647",
    "AbsCount": "2147483647",
    "LoopMode": "4",
    "PlayType": "10",
    "CurrentVolume": "24",
    "CurrentMute": "0",
    "CurrentChannel": "0",
    "SlaveFlag": "0",
    "MasterUUID": "",
    "SlaveList": "{ \"slaves\": 0, \"wmrm_version\": \"4.2\" }",
    "PlayMedium": "SONGLIST-NETWORK",
    "TrackSource": "Plex",
    "InternetAccess": "1",
    "VerUpdateFlag": "0",
    "VerUpdateStatus": "20",
    "BatteryFlag": "0",
    "BatteryPercent": "0",
    "AlarmFlag": "0",
    "TimeStamp": "69702767",
    "SubNum": "0",
    "SpotifyActive": "0",
    "metadataTimeStamp": 1729024669805
}`

**Comment by cvdlinden** [comment]
The upnp:albumArtURI property looks like it has been correctly populated. And to me it seems to get a thumbnail from the local network (Plex server), with your token. 

So I'm not sure why it isn't shown in the browser. I need to set up a Plex server myself in order to investigate... but my Synology NAS isn't cooperating, yet. ;)

**Comment by apwiggins** [comment]
I just had another peek at it now.  It looks like the server page reloaded when switching back from the /debug page.  So, it looks like it was a 'me' issue with a page reload being required.  Let's close this issue.
